#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Thu Jan 31 13:20:29 2019
#

import wx
import sys

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # Content of this block not found. Did you rename this class?
        pass

    def __set_properties(self):
        # Content of this block not found. Did you rename this class?
        pass

    def __do_layout(self):
        # Content of this block not found. Did you rename this class?
        pass

# end of class MainMenuBar
class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((701, 667))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Exit", "")
        self.Bind(wx.EVT_MENU, self.OnExit, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "About", "")
        self.Bind(wx.EVT_MENU, self.OnAbout, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.radio_box_1 = wx.RadioBox(self, wx.ID_ANY, " Select  ", choices=["choice 1     ", "choice 2", "choice 3"], majorDimension=3, style=wx.RA_SPECIFY_ROWS)
        self.btn_start = wx.Button(self, wx.ID_ANY, "Start")
        self.btn_stop = wx.Button(self, wx.ID_ANY, "Stop")
        self.button_3 = wx.Button(self, wx.ID_ANY, "button_3")
        self.sld_speed = wx.Slider(self, wx.ID_ANY, 0, 0, 100, style=wx.SL_AUTOTICKS | wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/heinz.samuelsson/python/wxglade/test4/aeroseum_logo_100x119.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBOX, self.OnSelected, self.radio_box_1)
        self.Bind(wx.EVT_BUTTON, self.OnStartClicked, self.btn_start)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Belting FUM Configuration")
        self.radio_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(2, 4, 4, 0)
        static_line_4 = wx.StaticLine(self, wx.ID_ANY)
        main_sizer.Add(static_line_4, 0, wx.BOTTOM | wx.EXPAND, 5)
        main_sizer.Add(self.radio_box_1, 0, wx.BOTTOM | wx.LEFT, 20)
        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        main_sizer.Add(static_line_1, 0, wx.BOTTOM | wx.EXPAND, 20)
        label_8 = wx.StaticText(self, wx.ID_ANY, "label_8")
        grid_sizer_1.Add(label_8, 0, wx.RIGHT, 10)
        label_11 = wx.StaticText(self, wx.ID_ANY, "label_11")
        grid_sizer_1.Add(label_11, 0, 0, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, "label_9")
        grid_sizer_1.Add(label_9, 0, wx.RIGHT, 10)
        label_12 = wx.StaticText(self, wx.ID_ANY, "label_12")
        grid_sizer_1.Add(label_12, 0, 0, 0)
        label_14 = wx.StaticText(self, wx.ID_ANY, "label_14")
        grid_sizer_1.Add(label_14, 0, 0, 0)
        label_15 = wx.StaticText(self, wx.ID_ANY, "label_15")
        grid_sizer_1.Add(label_15, 0, 0, 0)
        label_10 = wx.StaticText(self, wx.ID_ANY, "label_10")
        grid_sizer_1.Add(label_10, 0, wx.RIGHT, 10)
        label_13 = wx.StaticText(self, wx.ID_ANY, "label_13")
        grid_sizer_1.Add(label_13, 0, 0, 0)
        main_sizer.Add(grid_sizer_1, 0, wx.LEFT, 30)
        static_line_2 = wx.StaticLine(self, wx.ID_ANY)
        main_sizer.Add(static_line_2, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 20)
        main_sizer.Add(self.btn_start, 0, wx.BOTTOM | wx.LEFT, 15)
        main_sizer.Add(self.btn_stop, 0, wx.BOTTOM | wx.LEFT, 15)
        main_sizer.Add(self.button_3, 0, wx.LEFT, 15)
        static_line_3 = wx.StaticLine(self, wx.ID_ANY)
        main_sizer.Add(static_line_3, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 20)
        label_16 = wx.StaticText(self, wx.ID_ANY, "Set Speed")
        sizer_2.Add(label_16, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.sld_speed, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 50)
        sizer_2.Add(self.bitmap_1, 0, wx.ALIGN_CENTER, 0)
        main_sizer.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        self.Layout()
        # end wxGlade

    def OnSelected(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Radio button: ", self.radio_box_1.GetSelection())
	if (self.radio_box_1.GetSelection() == 2):
		self.sld_speed.Enable(False)
	if (self.radio_box_1.GetSelection() == 1):
		self.sld_speed.Enable(True)
	if (self.radio_box_1.GetSelection() == 0):
		self.bitmap_1.SetBitmap(wx.Bitmap("tea_100x100.png"))
        event.Skip()

    def OnStartClicked(self, event):  # wxGlade: MainFrame.<event_handler>
	self.sld_speed.SetValue(50)
        event.Skip()

    def OnExit(self, event):  # wxGlade: MainFrame.<event_handler>
	sys.exit()
        event.Skip()

    def OnAbout(self, event):  # wxGlade: MainFrame.<event_handler>
	info = wx.AboutDialogInfo()
	info.Name = "Belting FUM Configuration Tool"
	info.Version = "v1.0"
	info.License = "Do whatever you want, I don't care"
	info.Developers = ["Heinz Samuelsson"]
	wx.AboutBox(info)
        event.Skip()
# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
